### ISSUE TITLE
Build command to build the project

### ISSUE THREAD

**Issue by vikram919** [cose-wg/COSE-C#58]
Hello @jimsch 

make tests command result in test fail, what are the commands for correctly building cose-c ?

**Comment by jimsch** [comment]
d:\tools\cmake\bin\cmake -Dbuild_shared_libs=OFF -Duse_embedtls=ON  -G "Visual Studio 15 2017 Win64"

This is what I use based on the fact that I am using VS to do my work.  What target you use depends on what compiler you want.  Also you may want to set use_embedtls to off (the default).

Look at the CMAKE command line

**Comment by jimsch** [comment]
YOu can also look in the .travis.yml file for some command lines.

**Comment by vikram919** [comment]
I used to see where the test is failing `ctest -R RFC8152 -V` command: here is the info
```
UpdateCTestConfiguration  from :/home/****/COSE-C/DartConfiguration.tcl
Parse Config file:/home/****/COSE-C/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/*****/COSE-C/DartConfiguration.tcl
Parse Config file:/home/*****/COSE-C/DartConfiguration.tcl
Test project /home/*****/COSE-C
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 2
    Start 2: RFC8152

2: Test command: /home/*****/COSE-C/dist/test/cose_test "--dir" "Examples/RFC8152"
2: Test timeout computed to be: 1500
2: Cannot open directory 'Examples/RFC8152'
2: arg: '--dir'
2: arg: 'Examples/RFC8152'
1/1 Test #2: RFC8152 ..........................***Failed    0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec

The following tests FAILED:
	  2 - RFC8152 (Failed)
Errors while running CTest
```

**Comment by vikram919** [comment]
here are the steps I followed to build and install to includes folder:
1. git clone https://github.com/cose-wg/COSE-C.git
2. cd COSE-C/src
3. cmake CMakeLists.txt
4. sudo make
5. sudo make install - this install run time lib libcose-c.a, used as -lcose-c in gcc command
// below steps are done to provide .h files at compile time to project
6. mkdir cose-c
7.  cp cose.h ./cose-c
8. cp cose_init.h ./cose-c
9. configure.h ./cose-c
10. crypto.h ./cose-c
// finally
11. sudo mv cose-c /usr/local/include

I don't know whether this is the correct solution or not? but this solved my issue for now :-)

**Comment by jimsch** [comment]
This is a stupid on me.  I added tests for RSA and did not make sure that this was ignored here.

**Comment by jimsch** [comment]
No, that was not the problem.  Have you done a git on the examples directly recently?

**Comment by vikram919** [comment]
>  git on the examples directly recently?

I don't know this? can you please tell me how to do it?

**Comment by jimsch** [comment]
The tests assume that you have https://github.com/cose-wg/Examples as a subdirectory Examples of cose-c.  (see the git clone in .travis.yml)  You can have it someplace else but then you have to play some games.  This is the directory which contains all of the test examples that are used for all of my COSE libraries for testing.
