### ISSUE TITLE
How to validate COSE Sign0 by raw public key

### ISSUE THREAD

**Issue by hjian2017** [cose-wg/COSE-C#61]
Hi,
I found a API COSE_Sign0_validate, but it require a cn_cbor* format public key.  We always only have a public key like this:
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESn9zOanOXLrIMbtnBWia1th9PE9T
xOgD3r9dfkQz07+2HQ7MnkFW4UkMkbr+GuEESdi1b9mOowhXgeGpocV0AQ==
-----END PUBLIC KEY-----

Thanks:)

**Comment by jimsch** [comment]
The simplest method would be to write a quick and dirty routine that converts from the ASN.1 format to the COSE Key format.  How difficult this is depends on how many different public key formats you are going to want to support.  A full version would need to have an ASN.1 decoder, but many times one can find things based on fixed (or relatively fixed) offsets in the structure where one can just copy out of.

Which underling crypto library are you planning on using?

A far more complex method would be to define a new value in the COSE Key structure to hold this data, but that would require a great deal of work to change the underlying functions that interface with the crypto libraries to do.

**Comment by hjian2017** [comment]
Thanks for the reply.  I am planning to use mbedtls library.
I think both the methods you mentioned are good if cose-c can offer some examples.

**Comment by jimsch** [comment]
I had been hoping to find some time to just do this, but that does not seem to be in the offing.  So I am going to point you to some resources that you should be able to use to write some code.

The java version of the library is setup to be able to do this type of processing already.
https://github.com/cose-wg/COSE-JAVA/blob/master/src/main/java/COSE/ASN1.java - contains a small set of ASN.1 functions that are needed to decode and encode public keys

https://github.com/cose-wg/COSE-JAVA/blob/master/src/main/java/COSE/OneKey.java - has a set of functions that are mapping between the decoded public key structure and the COSE_Key structure.  An example of this can be found in the constructor for OneKey which access the JAVA objects PublicKey and PrivateKey.  The function generateOkpKey does the same type of work for EdDSA.

https://github.com/ARMmbed/mbed-os/blob/master/features/mbedtls/src/asn1parse.c - contains a set of functions that are implemented in mbed-tls that do the same type of ASN.1 parsing as the java file above.

I am going to assume that you know how to string the PEM structure and decode from base64 to binary.

**Comment by hjian2017** [comment]
@jimsch Thx for the help. I am still have an issue when try to validate a COSE_SIGN0 by a mbedtls_pk_context format public key.
-------------------------------------------------------------------------------------------------------------------------------------------
Here is how I sign it:
mbedtls_ecp_keypair *registrarPK = mbedtls_pk_ec(privateKey);

cn_cbor * regPK = cn_cbor_map_create(CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(regPK, COSE_Key_Type, cn_cbor_int_create(COSE_Key_Type_EC2, CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(regPK, COSE_Key_EC2_Curve, cn_cbor_int_create(1, CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(
regPK, -2,
cn_cbor_data_create((uint8_t *)registrarPK->Q.X.p, registrarPK->Q.X.n * 8, CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(
regPK, -3,
cn_cbor_data_create((uint8_t *)registrarPK->Q.Y.p, registrarPK->Q.Y.n * 8, CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(
regPK, -4,
cn_cbor_data_create((uint8_t *)registrarPK->Q.Z.p, registrarPK->Q.Z.n * 8, CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

COSE_Sign0_Sign(hEncObj, regPK, NULL);

-------------------------------------------------------------------------------------------------------------------------------------------
Here is how I validate it:
mbedtls_ecp_keypair *commissionerPubK = mbedtls_pk_ec(mDevCrt.pk);

cn_cbor * comPubK = cn_cbor_map_create(CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(comPubK, COSE_Key_Type, cn_cbor_int_create(COSE_Key_Type_EC2, CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(comPubK, COSE_Key_EC2_Curve, cn_cbor_int_create(1, CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(comPubK, -2,
cn_cbor_data_create((uint8_t *)commissionerPubK->Q.X.p, commissionerPubK->Q.X.n * 8,
CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

cn_cbor_mapput_int(comPubK, -3,
cn_cbor_data_create((uint8_t *)commissionerPubK->Q.Y.p, commissionerPubK->Q.Y.n * 8,
CBOR_CONTEXT_PARAM_COMMA NULL),
CBOR_CONTEXT_PARAM_COMMA NULL);

COSE_Sign0_validate(hEncObj, comPubK, NULL);
-------------------------------------------------------------------------------------------------------------------------------------------
It fails. Please help with it.

Thank you very much.
Best regards.

**Comment by jimsch** [comment]
First question, I assume that the value of n is in bytes?  If so I am not sure why you are doing the multiplication.  data create takes  byte pointer and a count in bytes.

**Comment by hjian2017** [comment]
Because registrarPK->Q.X.p is uint64_t*

**Comment by sbertin-telular** [comment]
n represents the allocated size, not necessarily the size of what is stored. Calling mbedtls_mpi_size(registrarPK->Q.X) is better, but could still be smaller than the point size. I would recommend calling mbedtls_mpi_write_binary to write the point to a temporary buffer of the correct size. Looking at  mbedtls_mpi_write_binary it looks like there is a change in byte order also.

**Comment by jimsch** [comment]
There are a couple of things that you should look at:

Firstly, the calculation you are doing might work correctly for P256, but would not be correct for P224 so that is a bit of a worry.  As suggested above, getting the size from mbedtl_mpi_size is probably a better idea as the value has to be of the correct number of bytes.  Even better would be the get the correct number of bytes from the curve data rather than from actual values of X, Y and Z. mbedtls_ecp_curve_info->bit_size is the value to be using.

Second, I would dump the public key structure from the PEM file and then compare the X and Y values from that structure against the uint8_t * value that you are looking at.  Depending on the chip you might have big-endian vs little-endian problems.  This should be easy to spot from looking at the byte string you have passed into the CBOR_data_create function.

Third, this is probably not the case here, but one of the fun problems that I have occasionally run across is that the first n bits of X or Y can be all zeros.  These zeros need to be preserved when passing in the X and Y values as these values need to be the same length as the key value.  For P256 this would be 256/8 bytes long.  I had a test that kept randomly failing on me because I was not verifying that this was true when I was first writing the C# version of the COSE library.

**Comment by hjian2017** [comment]
@sbertin-telular @jimsch 
Thx for the help.
You guys are right. The problem is about big-endian vs little-endian.

I fixed it as below:
`
byte   rgbX[128];

size_t size = mbedtls_ecp_curve_info_from_grp_id(commissionerPubK->grp.id)->bit_size / 8;

mbedtls_mpi_write_binary(&commissionerPubK->Q.X, rgbX, size);

cn_cbor_mapput_int(comPubK, COSE_Key_EC2_X,
                              cn_cbor_data_create((uint8_t *)rgbX, size, CBOR_CONTEXT_PARAM_COMMA NULL),
                              CBOR_CONTEXT_PARAM_COMMA NULL);
`

(BTW: registrarPK->Q.Z.p should be registrarPK->d.p when sign it)

**Comment by zhou-bin** [comment]
This is demo. It is ok in windows application(32 bits).
hSignObj = COSE_Sign0_Init(0, NULL);
    keypairEC = mbedtls_pk_ec(keypair);
    keypairCbor = cn_cbor_map_create( NULL);
    returnCode = cn_cbor_mapput_int(keypairCbor, COSE_Key_Type, cn_cbor_int_create(COSE_Key_Type_EC2, NULL), NULL);
    returnCode = mbedtls_ecp_point_write_binary(&keypairEC->grp, &keypairEC->Q, MBEDTLS_ECP_PF_UNCOMPRESSED, &keypairBinaryLength, keypairBinary, keypairBinaryLength);
    returnCode = cn_cbor_mapput_int(keypairCbor, COSE_Key_EC2_Curve, cn_cbor_int_create(1, NULL), NULL);
    returnCode = cn_cbor_mapput_int(
                                    keypairCbor,
                                    -2,
                                    cn_cbor_data_create(keypairBinary + 1, keypairEC->Q.X.n * 2, NULL),
                                    NULL
                                    );
    returnCode = cn_cbor_mapput_int(
                                    keypairCbor,
                                    -3,
                                    cn_cbor_data_create(keypairBinary + 1 + keypairEC->Q.X.n * 2, keypairEC->Q.Y.n * 2, NULL),
                                    NULL
                                    );
    memset(keypairBinary, 0, sizeof(keypairBinary));
    mbedtls_mpi_write_binary(&keypairEC->d, keypairBinary, keypairBinaryLength);
    returnCode = cn_cbor_mapput_int(
                                    keypairCbor,
                                    -4,
                                    cn_cbor_data_create(keypairBinary, keypairEC->d.n * 4, NULL),
                                    NULL
                                    );
    returnCode = base64_decode(x509Certificate, strlen(x509Certificate), x509DerData, &x509DerDataLength);
    x509Cbor = cn_cbor_data_create(x509DerData, x509DerDataLength, NULL);
    x509CborDataLength = cn_cbor_encoder_write(x509CertificateDataCbor, 0, CONSTANT_ANIMA_X509_LENGTH, x509Cbor);
    keyIDCbor = cn_cbor_data_create(x509CertificateDataCbor, x509CborDataLength, NULL);
    algorithmIDCbor = cn_cbor_int_create(COSE_Algorithm_ECDSA_SHA_256, NULL);
    returnCode = COSE_Sign0_map_put_int(hSignObj, COSE_Header_Algorithm, algorithmIDCbor, COSE_PROTECT_ONLY, NULL);
    returnCode = COSE_Sign0_map_put_int(hSignObj, COSE_Header_KID, keyIDCbor, COSE_UNPROTECT_ONLY, NULL);
    returnCode = COSE_Sign0_SetContent(hSignObj, payload, payloadLength, NULL);
    returnCode = COSE_Sign0_Sign(hSignObj, keypairCbor, NULL);
    coseLength = COSE_Encode((HCOSE)hSignObj, coseObject, (size_t)0, coseObjectLength);
    COSE_Sign0_Free(hSignObj);

**Comment by jimsch** [comment]
Assume that things worked
