### ISSUE TITLE
Doesn't support COSE sign1 ?

### ISSUE THREAD

**Issue by wgtdkp** [cose-wg/COSE-C#66]
It seems that this implementation doesn't support the COSE sign1 structure, true?

But the [COSE-JAVA](https://github.com/cose-wg/COSE-JAVA) seems support it. So, is any plan for adding COSE sign1 to COSE-C ?

**Comment by wgtdkp** [comment]
Or, does `COSE_Sign0` mean signed by a single signer? Why is it named like that?

**Comment by zhou-bin** [comment]
The COSE_Sign0_Sign api Maybe is  "Signature1".

COSE_Sign0_Sign->_COSE_Signer0_sign->CreateSign0AAD
   
CreateSign0AAD(pSigner, &pbToSign, &cbToSign, "Signature1", perr);

sorry my English.

**Comment by jimsch** [comment]
This is called varied movement forward on the code as the document changed.  The COSE structure was originally call Sign0 and not Sign1.  I changed it in the document and managed not to get all of the changes propagated back into all of the source code.  Changing the name is on my list of things to do, but if you want to give a pull request for this I would accept that too

**Comment by wgtdkp** [comment]
I can do that in my spare time.

**Comment by jimsch** [comment]
Fixed in the latest build
