### ISSUE TITLE
Issues with CMake

### ISSUE THREAD

**Issue by jimsch** [cose-wg/COSE-C#89]
I went to track down the gcov issue so I downloaded the system on to my Ubuntu machine.  I am running cmake version 3.10.2 on that system and I get the following error messages

jimsch@MyUbuntu:~/cose/cose-c/build$ cmake -DCOSE_C_USE_CONTEXT=OFF -DCOSE_C_USE_MBEDTLS=ON -DCOSE_C_COVERALLS=ON ..
Build type: Debug
-- adding GCC/Clang options 
CMake Error at CMakeLists.txt:181 (add_library):
  add_library cannot create ALIAS target "cn-cbor::cn-cbor" because target
  "cn-cbor" is IMPORTED.

You have called ADD_LIBRARY for library cose-c without any source files. This typically indicates a problem with your CMakeLists.txt file
COVERALLS UPLOAD: OFF
-- COSE_C_INCLUDE_ENCRYPT:..........ON
-- COSE_C_INCLUDE_ENCRYPT0:.........ON
-- COSE_C_INCLUDE_MAC:..............ON
-- COSE_C_INCLUDE_MAC0:.............ON
-- COSE_C_INCLUDE_SIGN:.............ON
-- COSE_C_INCLUDE_SIGN0:............ON
-- COSE_C_INCLUDE_SIGN1:............ON
-- COSE_C_USE_CONTEXT:..............OFF
-- COSE_C_FATAL_WARNINGS:...........OFF
-- COSE_C_BUILD_TESTS:..............ON
-- COSE_C_BUILD_DOCS:...............OFF
-- COSE_C_USE_MBEDTLS:..............ON
-- COSE_C_USE_FIND_PACKAGE:.........OFF
-- COSE_C_BUILD_DUMPER:.............ON
-- CMAKE_BUILD_TYPE:................Debug
-- BUILD_SHARED_LIBS:...............ON
-- COSE_VERSION:....................0.1.0
-- Configuring incomplete, errors occurred!
See also "/home/jimsch/cose/cose-c/build/CMakeFiles/CMakeOutput.log".

**Comment by jimsch** [comment]
@gocarlos  please look at this

**Comment by gocarlos** [comment]
I’ll have a look in a few minutes

**Comment by gocarlos** [comment]
are you on latest master?

**Comment by gocarlos** [comment]
line 181 is not `add_library`, probably you local copy is in a broken state?

**Comment by jimsch** [comment]
I just killed everything.  Recloned from the cose-wg version and now get the error on line 194

**Comment by gocarlos** [comment]
I still cannot reproduce it, I'm using cmake version 3.13.3, though I can understand it can be a bug in older versions of cmake... 

to fix the issue either:
* upgrade cmake to latest -> `pip install cmake --upgrade`
* replace `cn-cbor::cn-cbor` with `cn-cbor` in target_link_libraries and remove
```cmake
  if(NOT TARGET cn-cbor::cn-cbor)
    add_library(cn-cbor::cn-cbor ALIAS cn-cbor)
  endif()
```

I think option 1 is better as with https://github.com/cose-wg/COSE-C/pull/88 cmake 3.13 would be the minimum (released 2 years ago already)

**Comment by jimsch** [comment]
Upgrading to 3.17 fixed the problem.  Yes I would assume this is a 3.10 bug and we should upgrade the minimum version of cmake
